# Generated by Django 3.2.13 on 2022-04-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50, unique=True, verbose_name='Имя клиента')),
                ('client_id', models.CharField(max_length=30, unique=True, verbose_name='id клиента')),
                ('user_key', models.CharField(max_length=30, unique=True, verbose_name='Ключ клиента')),
                ('org', models.CharField(max_length=30, unique=True, verbose_name='Имя организации')),
                ('folder', models.CharField(max_length=30, verbose_name='Имя папки')),
                ('tenant', models.CharField(max_length=30, verbose_name='Имя тенанта')),
                ('user', models.EmailField(max_length=30, unique=True, verbose_name='Почта пользователя')),
            ],
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name': 'Почтовый адрес', 'verbose_name_plural': 'Почтовые адреса'},
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Почта'),
        ),
    ]
