# Generated by Django 3.2.13 on 2022-04-24 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0002_auto_20220424_1203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name': 'Разрешенный адрес запуска', 'verbose_name_plural': 'Разрешенные адреса запуска'},
        ),
        migrations.AddField(
            model_name='robots',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='robots.clients'),
        ),
    ]
