# Generated by Django 3.2.13 on 2022-04-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0003_auto_20220424_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='client_id',
            field=models.CharField(max_length=70, unique=True, verbose_name='id клиента'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='folder',
            field=models.CharField(max_length=70, verbose_name='Имя папки'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='org',
            field=models.CharField(max_length=70, unique=True, verbose_name='Имя организации'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='tenant',
            field=models.CharField(max_length=70, verbose_name='Имя тенанта'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='user',
            field=models.EmailField(max_length=70, unique=True, verbose_name='Почта пользователя'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='user_key',
            field=models.CharField(max_length=70, unique=True, verbose_name='Ключ клиента'),
        ),
    ]
